[package]
name = "api-client"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["wgpu", "tokio"] }
reqwest = { version = "0.12.23", features = ["blocking", "json"] }
serde_json = "1.0.142"
